# Generated by Django 5.0.6 on 2024-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=250, verbose_name='publisher'),
        ),
    ]
